pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                sh 'env'
                git branch: 'ros2', url: 'https://github.com/rkent/rosindex'
            }
        }
        stage('Build Image') {
            steps {
                sh 'docker/build.sh'
            }
        }
        stage('Build website') {
            steps {
                dir('docker') {
                    sh './run.sh ls'
                }
            }
        }
    }
}
