pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                sh 'env'
                git branch: 'ros2-test', url: 'https://github.com/rkent/rosindex'
            }
        }
        stage('Build Image') {
            steps {
                sh 'docker/build.sh'
            }
        }
        stage('Build website') {
            steps {
                sh 'docker/run.sh make build'
            }
        }
    }
}
