pipeline {
    agent { label 'ubuntu' }

    stages {
        stage('Docker build distro_clone') {
            steps {
                sh 'docker build -t distro_clone:$JOB_NAME common/distro_clone'
            }
        }
        stage('Clone distroclone') {
            steps {
                checkout poll: false, scm: scmGit(branches: [[name: 'refs/heads/main']], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'distroclone']], userRemoteConfigs: [[name: 'origin', url: 'https://github.com/rkent/distroclone']])
            }
        }
        stage('Docker clone distro with distroclone') {
            steps {
                sh 'docker rm -f $JOB_NAME || true'
                sh 'echo ROS_DISTRO is ${ROS_DISTRO}'
                sh 'echo REPO_MERGE_FILE is ${REPO_MERGE_FILE}'
                sh 'echo DESTINSTION is ${DESTINATION}'
                sh 'docker run --rm --name $JOB_NAME -v $WORKSPACE:/workspace -v /srv:/srv rosdoc2:$JOB_NAME run_distroclone ${ROS_DISTRO} /srv/repos/${ROS_DISTRO} ${REPO_MERGE_FILE}'
            }
        }
    }
    post {
        always {
            sh 'docker stop $JOB_NAME || true'
        }
    }
}
