pipeline {
    agent any

    environment{
        ROS_DISTRO = 'rolling'
        ROSDOC2_BRANCH = 'pr-main'
    }

    stages {
        stage('Docker build rosdoc2') {
            steps {
                sh 'docker build -t rosdoc2:$JOB_NAME /var/docker_farm/common/rosdoc2'
            }
        }
        stage('Clone rosdoc2') {
            steps {
                checkout poll: false, scm: scmGit(branches: [[name: "refs/heads/${ROSDOC2_BRANCH}"]], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'rosdoc2']], userRemoteConfigs: [[url: 'https://github.com/rkent/rosdoc2.git']])
            }
        }
        stage('Docker run rosdoc2') {
            steps {
                sh 'docker rm -f $JOB_NAME || true'
                sh 'rm -rf docs_build'
                sh 'rm -rf docs_output'
                sh 'docker run --rm --name $JOB_NAME -v $WORKSPACE:/workspace -v /data2:/data2 rosdoc2:$JOB_NAME run_rosdoc2 "scan -p /data2/repos/$ROS_DISTRO -t 3600 -u https://prrosdoc2.rosdabbler.com/${ROS_DISTRO}"'
            }
        }
        stage('Sync website') {
            steps {
                sh 'rsync -a --delete $WORKSPACE/docs_output/ /data2/prrosdoc2/${ROS_DISTRO}'
            }
        }
    }
    post {
        always {
            sh 'docker stop $JOB_NAME || true'
        }
    }
}
