pipeline {
    agent { label 'ubuntu' }
    stages {
        stage('Clone') {
            steps {
                sh 'env'
                git branch: 'rd-index', url: 'https://github.com/rkent/rosindex'
            }
        }
        stage('Build Image') {
            steps {
                sh 'docker/build.sh'
            }
        }
        stage('Build website') {
            steps {
                sh 'rm -rf _remotes'
                sh 'docker/run.sh make test-build'
            }
        }
        stage('Deploy website') {
            steps {
                sh 'pwd'
                sh 'common/deploy.sh'
            }
        }
    }
}
