pipeline {
    agent { label 'local' }
    stages {
        stage('Clone') {
            steps {
                sh 'env'
                git branch: 'rd-index', url: 'https://github.com/rkent/rosindex'
            }
        }
        stage('Build Image') {
            steps {
                sh 'docker/build.sh'
            }
        }
        /*
        stage('Build website') {
            steps {
                sh 'rm -rf _remotes'
                sh 'docker/run.sh make test-build'
            }
        }
        /**/
        stage('Deploy website') {
            steps {
                sh 'ssh-add -l'
                sh 'git config --global user.name "R. Kent James"'
                sh 'git config --global user.email "kent@caspia.com"'
                sh 'rm -rf _site/.git'
                sh 'git -C _site init -b main'
                sh 'git -C _site remote add origin git@github.com:rosdabbler/index.rosdabbler.com.git'
                sh 'git -C _site add .'
                sh 'git -C _site commit -m "Website publish"'
                sh 'git -C _site push -f --set-upstream origin main'
            }
        }
    }
}
