pipeline {
    agent { label 'agent4' }

    environment{
        ROS_DISTRO = 'jazzy'
    }

    stages {
        stage('Docker build') {
            steps {
                sh 'echo ROS_DISTRO is ${ROS_DISTRO}'
            }
        }
    }
}
