pipeline {
    agent { label 'ubuntu' }
    stages {
        stage('Clone') {
            steps {
                sh 'env'
                git branch: 'ros2-rkent', url: 'https://github.com/rkent/rosindex'
            }
        }
        stage('Build Image') {
            steps {
                sh 'docker/build.sh'
            }
        }
        stage('Build website') {
            steps {
                sh 'rm -rf _remotes'
                sh 'docker/run.sh make build'
            }
        }
        stage('Sync website') {
            steps {
                sh 'rsync --stats -ra --del _site /srv/devindex/'
            }
        }

    }
}
