pipeline {
    agent any
    stages {
        stage('Clone rosdoc2') {
            steps {
                checkout poll: false, scm: scmGit(branches: [[name: 'refs/heads/pr-main']], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'rosdoc2']], userRemoteConfigs: [[url: 'https://github.com/rkent/rosdoc2.git']])
            }
        }
        stage('Docker run rosdoc2') {
            steps {
                sh 'ln -s -f /ros2/jenkins/workspace/rosdoc2/checkout $WORKSPACE/checkout'
                sh 'docker rm -f rosdoc2_pr || true'
                sh 'docker run --rm --name rosdoc2_pr -v $WORKSPACE:/rosdoc2 rosdoc2:docker_farm run_rosdoc2 "scan -p $WORKSPACE/checkout -t 3600 "'
            }
        }
    }
    post {
        always {
            sh 'docker stop rosdoc2_pr || true'
        }
    }
}
